# Generated by Django 3.2.8 on 2021-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='category', max_length=250)),
                ('_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('common', 'Common'), ('admin', 'Admin'), ('company', 'Company')], db_column='role', default='common', max_length=20)),
                ('login', models.CharField(db_column='login', max_length=255, unique=True)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('surname', models.CharField(db_column='surname', max_length=250)),
            ],
        ),
    ]
