# Generated by Django 3.2.8 on 2021-10-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GIN.categories'),
        ),
    ]
